language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_install:
  # Install composer dependencies
  - composer self-update
  - composer update

  # Add the TravisCI config file
  - cp app/config.php.travisci app/config.php

  # Set up the database
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `pwx`;' -u root
  - mysql -e 'GRANT ALL ON `pwx`.* TO `pwx`@`localhost` IDENTIFIED BY "pwx";' -u root
  - app/console orm:schema-tool:create

script:
 # Run phpunit
  - vendor/bin/phpunit
