language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  # Install composer dependencies
  - composer self-update
  - composer update

  # Add the TravisCI config file
  - cp app/config.php.travisci app/config.php

  # Set up the database
  - app/console orm:schema-tool:create

script:
 # Run phpunit
  - vendor/bin/phpunit
